#!/bin/bash
# Regenerate the ReGreet login screen theme from the live caelestia palette.
#
# The greeter runs as the unprivileged `greeter` user, which cannot read
# /home/png (0700), so nothing under ~/.local/state or ~/.config can be
# referenced directly: the palette is rendered into /etc/greetd/regreet.css and
# the wallpaper is copied to /etc/greetd/background.<ext>, both world readable.
#
# Because of that copy, the greeter only follows the desktop palette when this
# script is re-run. Do that after changing scheme or wallpaper:
#
#     sudo scripts/greeter-theme.sh
#
# Pass a directory to write somewhere else instead, which needs no root and is
# how to preview a change before installing it:
#
#     scripts/greeter-theme.sh ~/.cache/greeter-preview
#     regreet --demo -s ~/.cache/greeter-preview/regreet.css
#
# Idempotent. See docs/login-greeter.md.

set -euo pipefail

OUT_DIR="${1:-/etc/greetd}"

if [[ $OUT_DIR == /etc/greetd && $EUID -ne 0 ]]; then
    echo "error: writing to /etc/greetd needs root (sudo $0)" >&2
    exit 1
fi

TARGET_USER="${SUDO_USER:-$USER}"
USER_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
SCHEME="$USER_HOME/.local/state/caelestia/scheme.json"
WALLPAPER="$USER_HOME/.local/state/caelestia/wallpaper/current"

if [[ ! -f $SCHEME ]]; then
    echo "error: no caelestia scheme at $SCHEME" >&2
    exit 1
fi

install -d -m 755 "$OUT_DIR"

# --- wallpaper ---------------------------------------------------------------
# `current` is a symlink into ~/Pictures; resolve it and copy the bytes out, so
# the greeter neither needs to traverse the home directory nor breaks when
# variety rotates the file away.
if [[ -e $WALLPAPER ]]; then
    src="$(readlink -f "$WALLPAPER")"
    ext="${src##*.}"
    rm -f "$OUT_DIR"/background.*
    install -m 644 "$src" "$OUT_DIR/background.$ext"
    # regreet.toml points at a fixed name, so keep one stable path too.
    ln -sfn "background.$ext" "$OUT_DIR/background"
    echo "    wallpaper: $(basename "$src") -> $OUT_DIR/background.$ext"
else
    echo "    no current wallpaper; leaving the greeter on a flat background"
fi

# --- stylesheet --------------------------------------------------------------
# ReGreet links plain GTK4 (no libadwaita), and GTK 4.16 moved the Adwaita theme
# from @define-color to CSS custom properties. Overriding only the old names is
# silently ignored on 4.16+, so both spellings are emitted: `:root { --... }`
# for current GTK, @define-color for anything older.
python3 - "$SCHEME" "$OUT_DIR/regreet.css" <<'PY'
import json
import sys

colours = json.load(open(sys.argv[1]))["colours"]
c = lambda name: "#" + colours[name]

# GTK/libadwaita named colour -> caelestia Material role.
roles = {
    "accent-bg-color": "primary",
    "accent-fg-color": "onPrimary",
    "accent-color": "primary",
    "window-bg-color": "background",
    "window-fg-color": "onBackground",
    "view-bg-color": "surfaceContainer",
    "view-fg-color": "onSurface",
    "headerbar-bg-color": "surfaceContainer",
    "headerbar-fg-color": "onSurface",
    "popover-bg-color": "surfaceContainerHigh",
    "popover-fg-color": "onSurface",
    "dialog-bg-color": "surfaceContainer",
    "dialog-fg-color": "onSurface",
    "card-bg-color": "surfaceContainer",
    "card-fg-color": "onSurface",
    "destructive-bg-color": "error",
    "destructive-fg-color": "onError",
    "destructive-color": "error",
    "error-bg-color": "error",
    "error-fg-color": "onError",
    "error-color": "error",
}

custom_props = "\n".join(f"    --{k}: {c(v)};" for k, v in roles.items())
define_colors = "\n".join(f"@define-color {k.replace('-', '_')} {c(v)};" for k, v in roles.items())

css = f"""/* Generated by scripts/greeter-theme.sh from the caelestia palette.
 * Do not edit: re-run `sudo scripts/greeter-theme.sh` instead. */

/* GTK >= 4.16 */
:root {{
{custom_props}
    --border-color: {c('outlineVariant')};
}}

/* GTK < 4.16 */
{define_colors}
@define-color borders {c('outlineVariant')};

/* The login form. ReGreet wraps it in a frame; float it over the wallpaper as a
 * rounded translucent surface, the way caelestia draws its own panels. */
frame {{
    background-color: alpha({c('surfaceContainer')}, 0.85);
    border: 1px solid alpha({c('outlineVariant')}, 0.6);
    border-radius: 20px;
    padding: 18px;
}}

/* The clock and the greeting sit directly on the wallpaper. */
label {{
    color: {c('onBackground')};
}}

entry, spinbutton, dropdown > button {{
    background-color: {c('surfaceContainerHighest')};
    color: {c('onSurface')};
    border-radius: 12px;
    min-height: 36px;
}}

entry:focus-within {{
    outline: 2px solid {c('primary')};
    outline-offset: -2px;
}}

button {{
    border-radius: 12px;
    min-height: 34px;
}}

button.suggested-action {{
    background-color: {c('primary')};
    color: {c('onPrimary')};
}}

button.destructive-action {{
    background-color: {c('error')};
    color: {c('onError')};
}}
"""

open(sys.argv[2], "w").write(css)
PY

chmod 644 "$OUT_DIR/regreet.css"
echo "    stylesheet: $OUT_DIR/regreet.css"

if [[ $OUT_DIR == /etc/greetd ]]; then
    # The package's tmpfiles rule creates these; make sure they exist on a fresh
    # install that has not run systemd-tmpfiles yet.
    install -d -o greeter -g greeter -m 755 /var/log/regreet /var/lib/regreet
    echo "done. The greeter picks this up at its next start."
fi
